version: "3.3"

services:
  server:
    container_name: shortLinks-server
    build:
      context: ./server/
    restart: always
    ports:
      - 3130:3130

  client:
    container_name: shortLinks-client
    build:
      context: ./client/
    restart: always
    ports:
      - 3100:80
